### ISSUE TITLE
few requests for raspbian-addons

### ISSUE THREAD

**Issue by mgrouch** [ryanfortner/ryanfortner#6]
few requests for raspbian-addons:

WxWidgets 3.2.x (libraries) - Buster and Bullseye needed
https://github.com/wxWidgets/wxWidgets/releases/tag/v3.2.0

Budgie-Desktop 10.6.2 - Buster and Bullseye needed
https://github.com/BuddiesOfBudgie/budgie-desktop/releases/tag/v10.6.2

Thanks for maintaining raspbian-addons.

**Comment by ryanfortner** [comment]
Hi there,

Both packages you requested are already in official Debian repositories. If you’d like me to compile and add the absolute latest versions of them, I can try to do that. However I’m away from home for a while so it might be a bit.

**Comment by mgrouch** [comment]
Yes. Exactly. They are way out of date in Debian with not much chances getting up to date

**Comment by ryanfortner** [comment]
Hi there, 

It's been awhile since you opened this issue and I apologize for the delay in assisting you. I'm currently very busy with classes. If you would be so kind as to open a package request on the raspbian-addons repository, I will get to it there. Thank you.

https://github.com/raspbian-addons/raspbian-addons/issues/new/choose
